# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('nation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('volume', models.IntegerField(default=1)),
                ('saga', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('note', models.FloatField()),
                ('summary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Author')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Editor')),
            ],
        ),
    ]
