# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_auto_20160216_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='saga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Saga'),
        ),
    ]
